[package]
name = "kenny_shooter"
version = "0.1.0"
authors = ["Dacode45 <davidrolandayeke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.1.2"